/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.uas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fadhilansyah25
 */
public class data_barangComboBox extends javax.swing.JFrame {
private Connection conn_FadilArdiansyah;
private Statement stat_FadilArdiansyah;
private ResultSet res_FadilArdiansyah;
    /**
     * Creates new form data_barang
     */
    public data_barangComboBox() {
        initComponents();
        koneksi();
        // kosongkan();
        tampil_combobox();
        tampil();
        // tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        harga_barangTextField = new javax.swing.JTextField();
        nama_barangTextField = new javax.swing.JTextField();
        tipe_barangComboBox = new javax.swing.JComboBox<>();
        ukuran_barangComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        stok_barangTextField = new javax.swing.JTextField();
        id_barangComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Input Data Barang");

        jLabel2.setText("Id Barang");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Tipe");

        jLabel5.setText("Ukuran");

        jLabel6.setText("Harga");

        nama_barangTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nama_barangTextFieldMouseClicked(evt);
            }
        });

        tipe_barangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galon", "Kardus Gelas", "Kardus Botol" }));
        tipe_barangComboBox.setSelectedIndex(-1);

        ukuran_barangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "240 ml", "330 ml", "450 ml", "600 ml", "750 ml", "1500 ml", "19 Liter", " " }));
        ukuran_barangComboBox.setSelectedIndex(-1);

        jLabel7.setText("Stok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(harga_barangTextField)
                            .addComponent(nama_barangTextField)
                            .addComponent(tipe_barangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ukuran_barangComboBox, 0, 134, Short.MAX_VALUE)
                            .addComponent(stok_barangTextField)
                            .addComponent(id_barangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipe_barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ukuran_barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(harga_barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stok_barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_barangTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_barangTextFieldMouseClicked
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_nama_barangTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barangComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barangComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barangComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barangComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barangComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga_barangTextField;
    private javax.swing.JComboBox<String> id_barangComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nama_barangTextField;
    private javax.swing.JTextField stok_barangTextField;
    private javax.swing.JComboBox<String> tipe_barangComboBox;
    private javax.swing.JComboBox<String> ukuran_barangComboBox;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn_FadilArdiansyah = DriverManager.getConnection("jdbc:mysql://127.0.0.1/jual_air", "root", "");
            stat_FadilArdiansyah = conn_FadilArdiansyah.createStatement();
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // private void kosongkan() {
    //     id_barangTextField.setText("");
    //     nama_barangTextField.setText("");
    //     tipe_barangComboBox.setSelectedIndex(-1);
    //     ukuran_barangComboBox.setSelectedIndex(-1);
    //     stok_barangTextField.setText("");
    //     harga_barangTextField.setText("");
    // }

    // private void tabel(){
    //     DefaultTableModel tabel = new DefaultTableModel();
    //     tabel.addColumn("ID Barang");
    //     tabel.addColumn("Nama Barang");
    //     tabel.addColumn("Ukuran");
    //     tabel.addColumn("Isi Volume");
    //     tabel.addColumn("Stok Barang");
    //     tabel.addColumn("Harga RP");
    //     Tabel_Barang.setModel(tabel);

    //     try {
    //         res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery("select * from t_barang");
    //         while (res_FadilArdiansyah.next()) {
    //             tabel.addRow(new Object[]
    //             {
    //                 res_FadilArdiansyah.getString("id_barang"),
    //                 res_FadilArdiansyah.getString("nama_barang"),
    //                 res_FadilArdiansyah.getString("tipe"),
    //                 res_FadilArdiansyah.getString("ukuran"),
    //                 res_FadilArdiansyah.getString("stok_barang"),
    //                 res_FadilArdiansyah.getString("harga_barang")
    //             });
    //         }
    //     } catch (Exception e) {
    //         //TODO: handle exception
    //         JOptionPane.showMessageDialog(null, e);
    //     }
    // }

    private void tampil_combobox() {
        try {
            String sql = "select id_barang from t_barang order by id_barang asc";
            res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery(sql);
            id_barangComboBox.addItem("-Pilih Kode Barang");
            while (res_FadilArdiansyah.next()) {
                id_barangComboBox.addItem(res_FadilArdiansyah.getString("id_barang"));
                
            }
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampil() {
        try {
            String sql = "select nama_barang, tipe, ukuran, harga_barang, stok_barang from t_barang where id_barang='"+id_barangComboBox.getSelectedItem()+"'";
            res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery(sql);

            while (res_FadilArdiansyah.next()) {
                {   
                    nama_barangTextField.setText(res_FadilArdiansyah.getString("nama_barang"));
                    tipe_barangComboBox.setSelectedItem(res_FadilArdiansyah.getString("tipe"));
                    ukuran_barangComboBox.setSelectedItem(res_FadilArdiansyah.getString("ukuran"));
                    harga_barangTextField.setText(res_FadilArdiansyah.getString("harga_barang"));
                    stok_barangTextField.setText(res_FadilArdiansyah.getString("stok_barang"));
                }
            }
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
}
