/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.uas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fadhilansyah25
 */
public class data_belanjaStok extends javax.swing.JFrame {
private Connection conn_FadilArdiansyah;
private Statement stat_FadilArdiansyah;
private ResultSet res_FadilArdiansyah;
    /**
     * Creates new form data_barang
     */
    public data_belanjaStok() {
        initComponents();
        koneksi();
        kosongkan();
        tabel();
        tampil_combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_belanjaTextField = new javax.swing.JTextField();
        nama_supplierTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Barang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jumlah_belanjaTextField = new javax.swing.JTextField();
        id_barangComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nama_barangTextField = new javax.swing.JTextField();
        refresh_tabelButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Belanja Stok");

        jLabel2.setText("Id Belanja");

        jLabel3.setText("Nama Supplier");

        jLabel6.setText("Id Barang");

        id_belanjaTextField.setEditable(false);

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        Tabel_Barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabel_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_BarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Barang);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Belanja");

        jumlah_belanjaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlah_belanjaTextFieldMouseClicked(evt);
            }
        });

        jLabel4.setText("Nama Barang");

        nama_barangTextField.setEditable(false);
        nama_barangTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nama_barangTextFieldMouseClicked(evt);
            }
        });

        refresh_tabelButton.setText("Refresh Tabel");
        refresh_tabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_tabelButtonActionPerformed(evt);
            }
        });

        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama_supplierTextField)
                            .addComponent(id_belanjaTextField)
                            .addComponent(id_barangComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_barangTextField)
                            .addComponent(jumlah_belanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembaliButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(simpanButton)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(refresh_tabelButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id_belanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nama_supplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(id_barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nama_barangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jumlah_belanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton)
                    .addComponent(jButton1)
                    .addComponent(editButton)
                    .addComponent(hapusButton)
                    .addComponent(refresh_tabelButton))
                .addGap(18, 18, 18)
                .addComponent(kembaliButton)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        try {
            stat_FadilArdiansyah.executeUpdate("insert into belanja_stok values (NULL,"
            +"'"+nama_supplierTextField.getText()+"',"
            +"'"+id_barangComboBox.getSelectedItem()+"',"
            +"'"+Integer.parseInt(jumlah_belanjaTextField.getText())+"')");
            kosongkan();
            tabel();

            JOptionPane.showMessageDialog(null, "Data Transaksi Berhasil Disimpan");
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void Tabel_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_BarangMouseClicked
        // TODO add your handling code here:
        int i_FadilArdiansyah = Tabel_Barang.getSelectedRow();
        if (i_FadilArdiansyah == -1) {
            return;
        }

        String code0_FadilArdiansyah = (String)Tabel_Barang.getValueAt(i_FadilArdiansyah, 0);
        String code1_FadilArdiansyah = (String)Tabel_Barang.getValueAt(i_FadilArdiansyah, 1);
        String code2_FadilArdiansyah = (String)Tabel_Barang.getValueAt(i_FadilArdiansyah, 2);
        String code3_FadilArdiansyah = (String)Tabel_Barang.getValueAt(i_FadilArdiansyah, 3);
        String code4_FadilArdiasnyah = (String)Tabel_Barang.getValueAt(i_FadilArdiansyah, 4);

        id_belanjaTextField.setText(code0_FadilArdiansyah);
        nama_supplierTextField.setText(code1_FadilArdiansyah);
        id_barangComboBox.setSelectedItem(code2_FadilArdiansyah);
        nama_barangTextField.setText(code3_FadilArdiansyah);
        jumlah_belanjaTextField.setText(code4_FadilArdiasnyah);
    }//GEN-LAST:event_Tabel_BarangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        int ok_FadilArdiansyah = JOptionPane.showConfirmDialog(null, "Apakah ingin mengedit Data ini?", "Edit Data", JOptionPane.YES_NO_CANCEL_OPTION);
        try {
            PreparedStatement stat_FadilArdiansyah = conn_FadilArdiansyah.prepareStatement(
                "update belanja_stok set id_belanja=?, nama_supplier=?, id_barang=?, jumlah_belanja=? where id_belanja='"
                +Integer.parseInt(id_belanjaTextField.getText())+"'");
                if (ok_FadilArdiansyah == 0) {
                    try {
                        stat_FadilArdiansyah.setInt(1, Integer.parseInt(id_belanjaTextField.getText()));
                        stat_FadilArdiansyah.setString(2, nama_supplierTextField.getText());
                        stat_FadilArdiansyah.setString(3, (String)id_barangComboBox.getSelectedItem());
                        stat_FadilArdiansyah.setInt(4, Integer.parseInt(jumlah_belanjaTextField.getText()));
                        stat_FadilArdiansyah.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Update Data Berhasil");
                    } catch (Exception e) {
                        //TODO: handle exception
                        JOptionPane.showMessageDialog(null, "Update Data Gagal"+e);
                    }
                }
            tabel();
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        int ok_FadilArdiansyah = JOptionPane.showConfirmDialog(null, "Apakah Yakin Menghapus Data?", "Hapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok_FadilArdiansyah == 0) {
            try {
                String sql_FadilArdiansyah = "delete from belanja_stok where id_belanja="+Integer.parseInt(id_belanjaTextField.getText());
                String resetno =  "ALTER TABLE belanja_stok DROP id_belanja";
                String consecutivenumbers = "ALTER TABLE belanja_stok ADD  id_belanja INT( 3 ) NOT NULL AUTO_INCREMENT FIRST ,ADD KEY (id_belanja)";
                PreparedStatement stat_FadilArdiansyah = conn_FadilArdiansyah.prepareStatement(sql_FadilArdiansyah);
                stat_FadilArdiansyah.executeUpdate();
                conn_FadilArdiansyah.createStatement().execute(resetno);
                conn_FadilArdiansyah.createStatement().execute(consecutivenumbers);
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            } catch (Exception e) {
                //TODO: handle exception
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal"+e);
            }
        }
        tabel();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void nama_barangTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_barangTextFieldMouseClicked
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_nama_barangTextFieldMouseClicked

    private void jumlah_belanjaTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlah_belanjaTextFieldMouseClicked
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_jumlah_belanjaTextFieldMouseClicked

    private void refresh_tabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_tabelButtonActionPerformed
        // TODO add your handling code here:
        tabel();
    }//GEN-LAST:event_refresh_tabelButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_belanjaStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_belanjaStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_belanjaStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_belanjaStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_belanjaStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_Barang;
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JComboBox<String> id_barangComboBox;
    private javax.swing.JTextField id_belanjaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_belanjaTextField;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JTextField nama_barangTextField;
    private javax.swing.JTextField nama_supplierTextField;
    private javax.swing.JButton refresh_tabelButton;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn_FadilArdiansyah = DriverManager.getConnection("jdbc:mysql://127.0.0.1/toko_galon", "root", "");
            stat_FadilArdiansyah = conn_FadilArdiansyah.createStatement();
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosongkan() {
        id_belanjaTextField.setText("");
        nama_supplierTextField.setText("");
        id_barangComboBox.setSelectedIndex(-1);
        nama_barangTextField.setText("");
        jumlah_belanjaTextField.setText("");
    }

    private void tabel(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Belanja");
        tabel.addColumn("Nama Supplier");
        tabel.addColumn("ID Barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Jumlah Belanja");
        Tabel_Barang.setModel(tabel);

        try {
            res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery("SELECT id_belanja, nama_supplier, jumlah_belanja, tabel_databarang.id_barang, tabel_databarang.nama_barang FROM belanja_stok INNER JOIN tabel_databarang ON belanja_stok.id_barang = tabel_databarang.id_barang");
            while (res_FadilArdiansyah.next()) {
                tabel.addRow(new Object[]
                {
                    res_FadilArdiansyah.getString("id_belanja"),
                    res_FadilArdiansyah.getString("nama_supplier"),
                    res_FadilArdiansyah.getString("tabel_databarang.id_barang"),
                    res_FadilArdiansyah.getString("tabel_databarang.nama_barang"),
                    res_FadilArdiansyah.getString("jumlah_belanja")
                });
            }
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampil_combobox() {
        try {
            String sql = "select id_barang from tabel_databarang order by id_barang asc";
            res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery(sql);
            id_barangComboBox.addItem("-Pilih Kode Barang");
            while (res_FadilArdiansyah.next()) {
                id_barangComboBox.addItem(res_FadilArdiansyah.getString("id_barang"));
                
            }
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampil() {
        try {
            String sql = "select nama_barang from tabel_databarang where id_barang='"+id_barangComboBox.getSelectedItem()+"'";
            res_FadilArdiansyah = stat_FadilArdiansyah.executeQuery(sql);

            while (res_FadilArdiansyah.next()) {
                {   
                    nama_barangTextField.setText(res_FadilArdiansyah.getString("nama_barang"));
                }
            }
        } catch (Exception e) {
            //TODO: handle exception
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
}
